/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResidentsRouteImport } from './routes/residents'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as FamilyPortalRouteImport } from './routes/family-portal'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as EmarRouteImport } from './routes/emar'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CarePlansRouteImport } from './routes/care-plans'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayInvoiceIdRouteImport } from './routes/pay.$invoiceId'

const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsRoute = ResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyPortalRoute = FamilyPortalRouteImport.update({
  id: '/family-portal',
  path: '/family-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const EmarRoute = EmarRouteImport.update({
  id: '/emar',
  path: '/emar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePlansRoute = CarePlansRouteImport.update({
  id: '/care-plans',
  path: '/care-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayInvoiceIdRoute = PayInvoiceIdRouteImport.update({
  id: '/pay/$invoiceId',
  path: '/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/care-plans': typeof CarePlansRoute
  '/compliance': typeof ComplianceRoute
  '/crm': typeof CrmRoute
  '/dining': typeof DiningRoute
  '/emar': typeof EmarRoute
  '/engagement': typeof EngagementRoute
  '/family-portal': typeof FamilyPortalRoute
  '/finances': typeof FinancesRoute
  '/maintenance': typeof MaintenanceRoute
  '/residents': typeof ResidentsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/workforce': typeof WorkforceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/care-plans': typeof CarePlansRoute
  '/compliance': typeof ComplianceRoute
  '/crm': typeof CrmRoute
  '/dining': typeof DiningRoute
  '/emar': typeof EmarRoute
  '/engagement': typeof EngagementRoute
  '/family-portal': typeof FamilyPortalRoute
  '/finances': typeof FinancesRoute
  '/maintenance': typeof MaintenanceRoute
  '/residents': typeof ResidentsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/workforce': typeof WorkforceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/care-plans': typeof CarePlansRoute
  '/compliance': typeof ComplianceRoute
  '/crm': typeof CrmRoute
  '/dining': typeof DiningRoute
  '/emar': typeof EmarRoute
  '/engagement': typeof EngagementRoute
  '/family-portal': typeof FamilyPortalRoute
  '/finances': typeof FinancesRoute
  '/maintenance': typeof MaintenanceRoute
  '/residents': typeof ResidentsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/workforce': typeof WorkforceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admissions'
    | '/analytics'
    | '/billing'
    | '/care-plans'
    | '/compliance'
    | '/crm'
    | '/dining'
    | '/emar'
    | '/engagement'
    | '/family-portal'
    | '/finances'
    | '/maintenance'
    | '/residents'
    | '/safety'
    | '/settings'
    | '/training'
    | '/workforce'
    | '/pay/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/admissions'
    | '/analytics'
    | '/billing'
    | '/care-plans'
    | '/compliance'
    | '/crm'
    | '/dining'
    | '/emar'
    | '/engagement'
    | '/family-portal'
    | '/finances'
    | '/maintenance'
    | '/residents'
    | '/safety'
    | '/settings'
    | '/training'
    | '/workforce'
    | '/pay/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admissions'
    | '/analytics'
    | '/billing'
    | '/care-plans'
    | '/compliance'
    | '/crm'
    | '/dining'
    | '/emar'
    | '/engagement'
    | '/family-portal'
    | '/finances'
    | '/maintenance'
    | '/residents'
    | '/safety'
    | '/settings'
    | '/training'
    | '/workforce'
    | '/pay/$invoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  CarePlansRoute: typeof CarePlansRoute
  ComplianceRoute: typeof ComplianceRoute
  CrmRoute: typeof CrmRoute
  DiningRoute: typeof DiningRoute
  EmarRoute: typeof EmarRoute
  EngagementRoute: typeof EngagementRoute
  FamilyPortalRoute: typeof FamilyPortalRoute
  FinancesRoute: typeof FinancesRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ResidentsRoute: typeof ResidentsRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  TrainingRoute: typeof TrainingRoute
  WorkforceRoute: typeof WorkforceRoute
  PayInvoiceIdRoute: typeof PayInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents': {
      id: '/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof ResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-portal': {
      id: '/family-portal'
      path: '/family-portal'
      fullPath: '/family-portal'
      preLoaderRoute: typeof FamilyPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emar': {
      id: '/emar'
      path: '/emar'
      fullPath: '/emar'
      preLoaderRoute: typeof EmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-plans': {
      id: '/care-plans'
      path: '/care-plans'
      fullPath: '/care-plans'
      preLoaderRoute: typeof CarePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$invoiceId': {
      id: '/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof PayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdmissionsRoute: AdmissionsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  CarePlansRoute: CarePlansRoute,
  ComplianceRoute: ComplianceRoute,
  CrmRoute: CrmRoute,
  DiningRoute: DiningRoute,
  EmarRoute: EmarRoute,
  EngagementRoute: EngagementRoute,
  FamilyPortalRoute: FamilyPortalRoute,
  FinancesRoute: FinancesRoute,
  MaintenanceRoute: MaintenanceRoute,
  ResidentsRoute: ResidentsRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  TrainingRoute: TrainingRoute,
  WorkforceRoute: WorkforceRoute,
  PayInvoiceIdRoute: PayInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
