/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResidentsRouteImport } from './routes/residents'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as FamilyPortalRouteImport } from './routes/family-portal'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as EmarRouteImport } from './routes/emar'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ClinicalRouteImport } from './routes/clinical'
import { Route as CarePlansRouteImport } from './routes/care-plans'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidentsIndexRouteImport } from './routes/residents.index'
import { Route as ResidentsRosterRouteImport } from './routes/residents.roster'
import { Route as ResidentsProfilesRouteImport } from './routes/residents.profiles'
import { Route as ResidentsAdmissionsRouteImport } from './routes/residents.admissions'
import { Route as PayInvoiceIdRouteImport } from './routes/pay.$invoiceId'

const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsRoute = ResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyPortalRoute = FamilyPortalRouteImport.update({
  id: '/family-portal',
  path: '/family-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const EmarRoute = EmarRouteImport.update({
  id: '/emar',
  path: '/emar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRoute = ClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePlansRoute = CarePlansRouteImport.update({
  id: '/care-plans',
  path: '/care-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsIndexRoute = ResidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResidentsRoute,
} as any)
const ResidentsRosterRoute = ResidentsRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => ResidentsRoute,
} as any)
const ResidentsProfilesRoute = ResidentsProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => ResidentsRoute,
} as any)
const ResidentsAdmissionsRoute = ResidentsAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => ResidentsRoute,
} as any)
const PayInvoiceIdRoute = PayInvoiceIdRouteImport.update({
  id: '/pay/$invoiceId',
  path: '/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/care-plans': typeof CarePlansRoute
  '/clinical': typeof ClinicalRoute
  '/compliance': typeof ComplianceRoute
  '/crm': typeof CrmRoute
  '/dining': typeof DiningRoute
  '/emar': typeof EmarRoute
  '/engagement': typeof EngagementRoute
  '/family-portal': typeof FamilyPortalRoute
  '/finances': typeof FinancesRoute
  '/maintenance': typeof MaintenanceRoute
  '/residents': typeof ResidentsRouteWithChildren
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/workforce': typeof WorkforceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/residents/admissions': typeof ResidentsAdmissionsRoute
  '/residents/profiles': typeof ResidentsProfilesRoute
  '/residents/roster': typeof ResidentsRosterRoute
  '/residents/': typeof ResidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/care-plans': typeof CarePlansRoute
  '/clinical': typeof ClinicalRoute
  '/compliance': typeof ComplianceRoute
  '/crm': typeof CrmRoute
  '/dining': typeof DiningRoute
  '/emar': typeof EmarRoute
  '/engagement': typeof EngagementRoute
  '/family-portal': typeof FamilyPortalRoute
  '/finances': typeof FinancesRoute
  '/maintenance': typeof MaintenanceRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/workforce': typeof WorkforceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/residents/admissions': typeof ResidentsAdmissionsRoute
  '/residents/profiles': typeof ResidentsProfilesRoute
  '/residents/roster': typeof ResidentsRosterRoute
  '/residents': typeof ResidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/care-plans': typeof CarePlansRoute
  '/clinical': typeof ClinicalRoute
  '/compliance': typeof ComplianceRoute
  '/crm': typeof CrmRoute
  '/dining': typeof DiningRoute
  '/emar': typeof EmarRoute
  '/engagement': typeof EngagementRoute
  '/family-portal': typeof FamilyPortalRoute
  '/finances': typeof FinancesRoute
  '/maintenance': typeof MaintenanceRoute
  '/residents': typeof ResidentsRouteWithChildren
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/workforce': typeof WorkforceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/residents/admissions': typeof ResidentsAdmissionsRoute
  '/residents/profiles': typeof ResidentsProfilesRoute
  '/residents/roster': typeof ResidentsRosterRoute
  '/residents/': typeof ResidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admissions'
    | '/analytics'
    | '/billing'
    | '/care-plans'
    | '/clinical'
    | '/compliance'
    | '/crm'
    | '/dining'
    | '/emar'
    | '/engagement'
    | '/family-portal'
    | '/finances'
    | '/maintenance'
    | '/residents'
    | '/safety'
    | '/settings'
    | '/training'
    | '/workforce'
    | '/pay/$invoiceId'
    | '/residents/admissions'
    | '/residents/profiles'
    | '/residents/roster'
    | '/residents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/admissions'
    | '/analytics'
    | '/billing'
    | '/care-plans'
    | '/clinical'
    | '/compliance'
    | '/crm'
    | '/dining'
    | '/emar'
    | '/engagement'
    | '/family-portal'
    | '/finances'
    | '/maintenance'
    | '/safety'
    | '/settings'
    | '/training'
    | '/workforce'
    | '/pay/$invoiceId'
    | '/residents/admissions'
    | '/residents/profiles'
    | '/residents/roster'
    | '/residents'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admissions'
    | '/analytics'
    | '/billing'
    | '/care-plans'
    | '/clinical'
    | '/compliance'
    | '/crm'
    | '/dining'
    | '/emar'
    | '/engagement'
    | '/family-portal'
    | '/finances'
    | '/maintenance'
    | '/residents'
    | '/safety'
    | '/settings'
    | '/training'
    | '/workforce'
    | '/pay/$invoiceId'
    | '/residents/admissions'
    | '/residents/profiles'
    | '/residents/roster'
    | '/residents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  CarePlansRoute: typeof CarePlansRoute
  ClinicalRoute: typeof ClinicalRoute
  ComplianceRoute: typeof ComplianceRoute
  CrmRoute: typeof CrmRoute
  DiningRoute: typeof DiningRoute
  EmarRoute: typeof EmarRoute
  EngagementRoute: typeof EngagementRoute
  FamilyPortalRoute: typeof FamilyPortalRoute
  FinancesRoute: typeof FinancesRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ResidentsRoute: typeof ResidentsRouteWithChildren
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  TrainingRoute: typeof TrainingRoute
  WorkforceRoute: typeof WorkforceRoute
  PayInvoiceIdRoute: typeof PayInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents': {
      id: '/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof ResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-portal': {
      id: '/family-portal'
      path: '/family-portal'
      fullPath: '/family-portal'
      preLoaderRoute: typeof FamilyPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emar': {
      id: '/emar'
      path: '/emar'
      fullPath: '/emar'
      preLoaderRoute: typeof EmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical': {
      id: '/clinical'
      path: '/clinical'
      fullPath: '/clinical'
      preLoaderRoute: typeof ClinicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-plans': {
      id: '/care-plans'
      path: '/care-plans'
      fullPath: '/care-plans'
      preLoaderRoute: typeof CarePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents/': {
      id: '/residents/'
      path: '/'
      fullPath: '/residents/'
      preLoaderRoute: typeof ResidentsIndexRouteImport
      parentRoute: typeof ResidentsRoute
    }
    '/residents/roster': {
      id: '/residents/roster'
      path: '/roster'
      fullPath: '/residents/roster'
      preLoaderRoute: typeof ResidentsRosterRouteImport
      parentRoute: typeof ResidentsRoute
    }
    '/residents/profiles': {
      id: '/residents/profiles'
      path: '/profiles'
      fullPath: '/residents/profiles'
      preLoaderRoute: typeof ResidentsProfilesRouteImport
      parentRoute: typeof ResidentsRoute
    }
    '/residents/admissions': {
      id: '/residents/admissions'
      path: '/admissions'
      fullPath: '/residents/admissions'
      preLoaderRoute: typeof ResidentsAdmissionsRouteImport
      parentRoute: typeof ResidentsRoute
    }
    '/pay/$invoiceId': {
      id: '/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof PayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResidentsRouteChildren {
  ResidentsAdmissionsRoute: typeof ResidentsAdmissionsRoute
  ResidentsProfilesRoute: typeof ResidentsProfilesRoute
  ResidentsRosterRoute: typeof ResidentsRosterRoute
  ResidentsIndexRoute: typeof ResidentsIndexRoute
}

const ResidentsRouteChildren: ResidentsRouteChildren = {
  ResidentsAdmissionsRoute: ResidentsAdmissionsRoute,
  ResidentsProfilesRoute: ResidentsProfilesRoute,
  ResidentsRosterRoute: ResidentsRosterRoute,
  ResidentsIndexRoute: ResidentsIndexRoute,
}

const ResidentsRouteWithChildren = ResidentsRoute._addFileChildren(
  ResidentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdmissionsRoute: AdmissionsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  CarePlansRoute: CarePlansRoute,
  ClinicalRoute: ClinicalRoute,
  ComplianceRoute: ComplianceRoute,
  CrmRoute: CrmRoute,
  DiningRoute: DiningRoute,
  EmarRoute: EmarRoute,
  EngagementRoute: EngagementRoute,
  FamilyPortalRoute: FamilyPortalRoute,
  FinancesRoute: FinancesRoute,
  MaintenanceRoute: MaintenanceRoute,
  ResidentsRoute: ResidentsRouteWithChildren,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  TrainingRoute: TrainingRoute,
  WorkforceRoute: WorkforceRoute,
  PayInvoiceIdRoute: PayInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
